project_name: tickgit
before:
  hooks:
    - go mod tidy
builds:
-
  main: ./cmd/tickgit/tickgit.go
  env:
    - CGO_ENABLED=0
brews:
-
  github:
    owner: augmentable-dev
    name: homebrew-tickgit
  commit_author:
    name: tickgit
    email: support@tickgit.com
  homepage: "https://www.tickgit.com/"
  description: "Surface TODO comments in any codebase"

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
